### ISSUE TITLE
Milestone 7-Submission-Sprint 4

### ISSUE THREAD

**Issue by hatu87** [Major-League-Boiler-Makers/HackathonIOS#16]
:+1: Thanks for submitting your progress for this sprint! Next week we go into the final sprint before demo day. Make sure you leave enough time to put together and practice your demo.

I didn't see your updated features in gif file. Please update it.

**Comment by Deadlocked007** [comment]
@hatu87 Oh my totally forgot about that, haha. We've been busy getting ready for our demo day tomorrow so I've updated it now though!
