### ISSUE TITLE
33% user stories complete /cc @codepathreview

### ISSUE THREAD

**Issue by Deadlocked007** [Major-League-Boiler-Makers/HackathonIOS#5]

**Comment by Deadlocked007** [comment]
@codepathreveiw

**Comment by Deadlocked007** [comment]
@codepathreview

**Comment by hatu87** [comment]
Hi, did you split works to your teammates? Please submit your work break down to github using github issues.

**Comment by Deadlocked007** [comment]
Hi, the work assignments are already put down under the "work assignment" section in the readme. Should I move it closer to the top?  Also if it's not a bother could we possibly be given an example of a proper readme? It's actually the first time the members of this group including myself have worked on a project of this scale let alone documenting one so we're really confused haha.
