### ISSUE TITLE
Required stories completed @codepathreview

### ISSUE THREAD

**Issue by Deadlocked007** [Major-League-Boiler-Makers/HackathonIOS#7]

**Comment by hatu87** [comment]
:+1: Great job getting all the required stories done! This is a big milestone as now it's all about adding optionals and additional polish to the app.

Besides, there are a few things you can consider:
 - You can use Github issues to organise your tasks like this repository: https://github.com/QSport/QSport/issues
 - Hackathon information is not enough for developers. We can show history of hackathons like: winners, last ideas, participants, images, videos, etc.
 - How can an hackathon host can post new one to your app?
 - Allow users to switch views between map view, which show all of hackathons around the developer and thumbnail view.

**Comment by Deadlocked007** [comment]
@hatu87 Thank you for the feedback once again! As for you points:

- I'll try to structure the tasks better this week
- As of this point accessing data like that would require me to either hard code in the data for each individual hackathons to the api or make an API for each individual hackathons page. I don't know if this is doable before the end of the semester since I have classes and stuff but I'll try my best if that is what is needed. Preferably since I'd like to publish this app I was wondering if Codepath could help me reach out to MLH to see if they have a private API I could use or a way they could help me like building an API or the likes. I've been researching but I still don't know the proper way to go about doing it.
- Also depends on MLH cooperation.
- You can already switch between views using the tabs on the bottom. I haven't labeled them yet but they are there.

Thank you for your time!
